apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-payment-pvc
  namespace: innowise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-db
  namespace: innowise
spec:
  serviceName: payment-db
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "payment_service"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME_PAYMENT
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD_PAYMENT
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d payment_service
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d payment_service
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-payment-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: innowise
spec:
  selector:
    app: payment-db
  ports:
    - port: 5432
      targetPort: 5432