apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: innowise
type: Opaque
data:
  JWT_SECRET: bXlWZXJ5U2VjcmV0S2V5Rm9ySldUR2VuZXJhdGlvbkluQXV0aFNlcnZpY2UyMDI0V2l0aE1pbmltdW0zMkNoYXJhY3RlcnM=
  API_GATEWAY_INTERNAL_TOKEN: Z2F0ZXdheS1pbnRlcm5hbC1zZWNyZXQtMjAyNA==
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: innowise
type: Opaque
data:
  # --- Auth Service DB ---
  DB_URL_AUTH: amRiYzpwb3N0Z3Jlc3FsOi8vYXV0aC1kYjo1NDMyL2F1dGhfc2VydmljZQ==      # jdbc:postgresql://auth-db:5432/auth_service
  DB_USERNAME_AUTH: cG9zdGdyZXM=  # postgres
  DB_PASSWORD_AUTH: cGFzc3dvcmQ=  # password

  # --- User Service DB ---
  DB_URL_USER: amRiYzpwb3N0Z3Jlc3FsOi8vdXNlci1kYjo1NDMyL3VzZXJfc2VydmljZQ==       # jdbc:postgresql://user-db:5432/user_service
  DB_USERNAME_USER: cG9zdGdyZXM=   # postgres
  DB_PASSWORD_USER: cGFzc3dvcmQ=   # password

  # --- Order Service DB ---
  DB_URL_ORDER: amRiYzpwb3N0Z3Jlc3FsOi8vb3JkZXItZGI6NTQzMi9vcmRlcl9zZXJ2aWNl   # jdbc:postgresql://order-db:5432/order_service
  DB_USERNAME_ORDER: cG9zdGdyZXM=  # postgres
  DB_PASSWORD_ORDER: cGFzc3dvcmQ=  # password

  # --- Payment Service DB ---
  DB_URL_PAYMENT: amRiYzpwb3N0Z3Jlc3FsOi8vcGF5bWVudC1kYjo1NDMyL3BheW1lbnRfc2VydmljZQ==  # jdbc:postgresql://payment-db:5432/payment_service
  DB_USERNAME_PAYMENT: cG9zdGdyZXM=  # postgres
  DB_PASSWORD_PAYMENT: cGFzc3dvcmQ=  # password