apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: innowise
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: [ "sh", "-c", "until nc -z order-db 5432; do sleep 3; done" ]
        - name: wait-for-kafka
          image: busybox:1.36
          command: [ "sh", "-c", "until nc -z kafka 9092; do sleep 3; done" ]
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_URL_ORDER
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME_ORDER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD_ORDER
            - name: SPRING_LIQUIBASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_URL_ORDER
            - name: SPRING_LIQUIBASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME_ORDER
            - name: SPRING_LIQUIBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD_ORDER
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: API_GATEWAY_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_GATEWAY_INTERNAL_TOKEN
            - name: SPRING_CONFIG_LOCATION
              value: "file:/app/config/application.yml"
            - name: SPRING_LIQUIBASE_ENABLED
              value: "true"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "order-service-payment-events"
            - name: KAFKA_TOPIC_PAYMENT_EVENTS
              value: "payment-events"
            - name: USER_SERVICE_URL
              value: "http://user-service:8080"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /app/config/application.yml
              subPath: application.yml
      volumes:
        - name: config
          configMap:
            name: order-service-config